export const tapColors = {
  primary: '#3580e6',
  default: `#5e6e82`,
  link: '#307de5',
  success: '#048851',
  warning: '#fce7eb',
  danger: '#e63b5a',
  backGround: '#edf2f9',
  sidebarBackground: '#ffffff',
  appBackground: '#edf2f9',
  fontSize: '14px',
  headingColor: 'rgba(0, 0, 0, 0.85)',
  textColor: 'rgba(0, 0, 0, 0.65)',
  textColorSecondary : 'rgba(0, 0, 0, .45)',
  textColorAlt: '#ffffff', 
  disabledColor : 'rgba(0, 0, 0, .25)',
  borderRadius: '4px',
  borderColor: '#5e6e82',
  headerBackground: '#ffffff',
  shadowColor: '#000',
  inactive: `#a6b0c0`,
  accentBackground: '#f9fafe',
  border: `#ebf3fc`,
}

// Example : http://snpy.in/EuGKsu
const extracted = {
  primary: `#3580e6`,
  default: `#5e6e82`,
  background: `#edf2f9`,
  highlight: `#048851`,
  highlightBg: `#e0faef`,
  highlightAlt: `#27bcfd`,
  highlightAltBg: `#e5f7ff`,
  warn: `#fce7eb`,
  warnBg: `#fef0e8`,
  danger: `#e0faef`,
  dangerBg: `#fce7eb`,
  link: `#307de5`,
}