import { noOp } from '@keg-hub/jsutils'

export {
  noOp as accessibility,
  noOp as addInitScript,
  noOp as bringToFront,
  noOp as close,
  noOp as context,
  noOp as coverage,
  noOp as emulateMedia,
  noOp as goBack,
  noOp as goForward,
  noOp as goto,
  noOp as isClosed,
  noOp as keyboar,
  noOp as mainFrame,
  noOp as mous,
  noOp as opener,
  noOp as pdf,
  noOp as reload,
  noOp as route,
  noOp as screenshot,
  noOp as setContent,
  noOp as setDefaultNavigationTimeout,
  noOp as setDefaultTimeout,
  noOp as setExtraHTTPHeaders,
  noOp as setInputFiles,
  noOp as setViewportSize,
  noOp as tap,
  noOp as title,
  noOp as touchscree,
  noOp as unroute,
  noOp as url,
  noOp as video,
  noOp as viewportSize,
  noOp as workers,
}